### PR TITLE
Assignment-2 completed

### PR DESCRIPTION
**Pull request by Daya709**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Submitting Assignment_2 of ASC
## What did you learn from the changes you have made?
Learned linear regressing. Splitting, fitting, and assessing the model accuracy.
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
Not at this time
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I was unable to split the training and test set properly
## How were these changes tested?
These changes were tested in vs code
## A reference to a related issue in your repository (if applicable)
na
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by KasraVakiloroayaei** [comment]
A2: Incomplete 

Q1 part (i) you must specify the number of columns 
Q1 part (ii) you must explain what it is in short? (1-2 sentences at max). Not only state it is float64
Q1 part (iii) The question is asking to list the top 5 rows in which HP (horsepower) is largest 
Q1 part(iv) The dataset has more than 5 predictors, please take a closer look

Q2 part (i) what about cylinders vs mpg, what is the association for that plot ? 
Q2 part (ii) More specifically it is a line of best fit, that is looking to minimize the squared distance from the fitted regression line and the plot of points

Q3 did not complete step 2 correctly. try refitting the model in a different way 

Q4 np.mean is not the correct function to call here. RMSE is a single numeric value that you should have for your output

**Comment by Daya709** [comment]
Hi, 
Thank you for your comments! I tried X_train, X_test, y_train, and y_test but could not generate an equal number of rows on both train sets. Other than that, all the comments were addressed.

**Comment by KasraVakiloroayaei** [comment]
A2: Incomplete 

Q1 part (iii) I swould suggest trying .nlargest() to list the top 5 rows with highest Horsepower 
Q2 Part (i) Solution is Missing 
Q3 please try the following line of code "numeric_predictors = mpg_train.select_dtypes(include=[float, int]).drop(columns=['mpg'])". Reflect on what this line of code is attempting to achieve, then fit your linear model from there. 
Q4 Changes still need to be made.

**Comment by Daya709** [comment]
Hi Melokazz, 
Q2. I am still unable to fix the Q3 as you mentioned, it is giving the unequal number of x_train and y_train. I couldn't find you in slack. It would be great if we could talk.

**Pull request merged**
